// THIS FILE IS AUTO-GENERATED BY @tanstack/react-router's Vite plugin.
// DO NOT EDIT MANUALLY — it is regenerated on every `pnpm dev` / `pnpm build`.
// This stub is committed so that `tsc --noEmit` passes before the first dev run.

import type { FileRoutesByPath } from "@tanstack/react-router";

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": { id: "/"; path: "/"; fullPath: "/" };
    "/_dev": { id: "/_dev"; path: "/_dev"; fullPath: "/_dev" };
    "/_dev/components": {
      id: "/_dev/components";
      path: "/components";
      fullPath: "/_dev/components";
    };
    "/_dev/templates/$slug": {
      id: "/_dev/templates/$slug";
      path: "/templates/$slug";
      fullPath: "/_dev/templates/$slug";
    };
  }
}

// The real routeTree is generated at runtime by the Vite plugin.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const routeTree = {} as any;
