/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DevRouteImport } from './routes/_dev'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevComponentsRouteImport } from './routes/_dev/components'
import { Route as DevTemplatesSlugRouteImport } from './routes/_dev/templates.$slug'

const DevRoute = DevRouteImport.update({
  id: '/_dev',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevComponentsRoute = DevComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => DevRoute,
} as any)
const DevTemplatesSlugRoute = DevTemplatesSlugRouteImport.update({
  id: '/templates/$slug',
  path: '/templates/$slug',
  getParentRoute: () => DevRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components': typeof DevComponentsRoute
  '/templates/$slug': typeof DevTemplatesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components': typeof DevComponentsRoute
  '/templates/$slug': typeof DevTemplatesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dev': typeof DevRouteWithChildren
  '/_dev/components': typeof DevComponentsRoute
  '/_dev/templates/$slug': typeof DevTemplatesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/components' | '/templates/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/components' | '/templates/$slug'
  id: '__root__' | '/' | '/_dev' | '/_dev/components' | '/_dev/templates/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevRoute: typeof DevRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dev': {
      id: '/_dev'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dev/components': {
      id: '/_dev/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof DevComponentsRouteImport
      parentRoute: typeof DevRoute
    }
    '/_dev/templates/$slug': {
      id: '/_dev/templates/$slug'
      path: '/templates/$slug'
      fullPath: '/templates/$slug'
      preLoaderRoute: typeof DevTemplatesSlugRouteImport
      parentRoute: typeof DevRoute
    }
  }
}

interface DevRouteChildren {
  DevComponentsRoute: typeof DevComponentsRoute
  DevTemplatesSlugRoute: typeof DevTemplatesSlugRoute
}

const DevRouteChildren: DevRouteChildren = {
  DevComponentsRoute: DevComponentsRoute,
  DevTemplatesSlugRoute: DevTemplatesSlugRoute,
}

const DevRouteWithChildren = DevRoute._addFileChildren(DevRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevRoute: DevRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
